# Generated by Django 5.0.6 on 2024-10-11 01:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="variety",
            name="has_price",
            field=models.BooleanField(default=False),
        ),
    ]
