# Generated by Django 5.0.6 on 2025-01-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_variety_has_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="price",
            name="quality",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "Primera calidad"),
                    ("2", "Segunda calidad"),
                    ("3", "Tercera calidad"),
                ],
                max_length=63,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="price",
            name="sale_format",
            field=models.CharField(
                blank=True,
                choices=[
                    ("suelta", "Suelta"),
                    ("trenza", "Trenza"),
                    ("corriente", "Corriente"),
                    ("parafinada", "Parafinada"),
                ],
                max_length=63,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="price",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[("P", "Pequeño"), ("M", "Mediano"), ("G", "Grande")],
                max_length=63,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="price",
            name="unit",
            field=models.CharField(
                choices=[
                    ("kg", "Kilogramo"),
                    ("u", "Unidad"),
                    ("rollo", "Rollo"),
                    ("mata", "Mata"),
                ],
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="variety",
            name="variety_id",
            field=models.CharField(
                max_length=127, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
