# Generated by Django 5.0.6 on 2025-01-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_price_quality_price_sale_format_price_size_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price",
            name="price_id",
            field=models.CharField(max_length=127, primary_key=True, serialize=False),
        ),
    ]
