# Generated by Django 5.0.6 on 2024-10-10 23:25

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("marketplaces", "0001_initial"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketplaceEdit",
            fields=[
                (
                    "marketplace_edit_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=127)),
                (
                    "name_alternate",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("opening_date", models.DateField(blank=True, null=True)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "area",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("province", models.CharField(blank=True, max_length=31, null=True)),
                ("canton", models.CharField(blank=True, max_length=31, null=True)),
                ("district", models.CharField(blank=True, max_length=31, null=True)),
                ("postal_code", models.IntegerField(blank=True, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("S", "Pequeña"),
                            ("M", "Mediana"),
                            ("L", "Grande"),
                            ("XL", "Muy grande"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                ("operator", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "branch",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Atlántico", "Comité Regional Atlántico"),
                            ("Brunca", "Comité Regional Brunca"),
                            ("Central Central", "Comité Regional Central Central"),
                            (
                                "Central Occidental Este",
                                "Comité Regional Central Occidental Este",
                            ),
                            (
                                "Central Occidental Oeste",
                                "Comité Regional Central Occidental Oeste",
                            ),
                            ("Central Oriental", "Comité Regional Central Oriental"),
                            ("Chorotega", "Comité Regional Chorotega"),
                            ("Huetar Norte", "Comité Regional Huetar Norte"),
                            ("Pacífico Central", "Comité Regional Pacífico Central"),
                        ],
                        max_length=63,
                        null=True,
                    ),
                ),
                ("parking", models.BooleanField(blank=True, default=None, null=True)),
                (
                    "bicycle_parking",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "fairground",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                ("indoor", models.BooleanField(blank=True, default=None, null=True)),
                ("toilets", models.BooleanField(blank=True, default=None, null=True)),
                (
                    "handwashing",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "drinking_water",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                ("food", models.BooleanField(blank=True, default=None, null=True)),
                ("drinks", models.BooleanField(blank=True, default=None, null=True)),
                (
                    "handicrafts",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                ("butcher", models.BooleanField(blank=True, default=None, null=True)),
                ("dairy", models.BooleanField(blank=True, default=None, null=True)),
                ("seafood", models.BooleanField(blank=True, default=None, null=True)),
                (
                    "garden_centre",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                ("florist", models.BooleanField(blank=True, default=None, null=True)),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "submitted_by",
                    models.CharField(blank=True, max_length=127, null=True),
                ),
                (
                    "submitted_by_role",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "submitted_by_contact",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("submitted_on", models.DateTimeField(auto_now_add=True)),
                ("is_reviewed", models.BooleanField(default=False)),
                (
                    "marketplace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="marketplaces.marketplace",
                    ),
                ),
                (
                    "payment",
                    models.ManyToManyField(blank=True, to="marketplaces.payment"),
                ),
                ("products", models.ManyToManyField(blank=True, to="products.product")),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmailEdit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=127, null=True)),
                ("type", models.CharField(blank=True, max_length=31, null=True)),
                ("is_reviewed", models.BooleanField(default=False)),
                (
                    "marketplace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="marketplaces.marketplace",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "marketplace_edit_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crowdsourcing.marketplaceedit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MarketplaceProductsEdit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("varieties", models.JSONField(blank=True, null=True)),
                (
                    "submitted_by",
                    models.CharField(blank=True, max_length=127, null=True),
                ),
                ("is_reviewed", models.BooleanField(default=False)),
                (
                    "marketplace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="marketplaces.marketplace",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OpeningHoursEdit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_opens",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Mo", "Lunes"),
                            ("Tu", "Martes"),
                            ("We", "Miércoles"),
                            ("Th", "Jueves"),
                            ("Fr", "Viernes"),
                            ("Sa", "Sábado"),
                            ("Su", "Domingo"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                ("hour_opens", models.TimeField(blank=True, null=True)),
                (
                    "day_closes",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Mo", "Lunes"),
                            ("Tu", "Martes"),
                            ("We", "Miércoles"),
                            ("Th", "Jueves"),
                            ("Fr", "Viernes"),
                            ("Sa", "Sábado"),
                            ("Su", "Domingo"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                ("hour_closes", models.TimeField(blank=True, null=True)),
                ("is_reviewed", models.BooleanField(default=False)),
                (
                    "marketplace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="marketplaces.marketplace",
                    ),
                ),
                (
                    "marketplace_edit_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crowdsourcing.marketplaceedit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PhoneEdit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.TextField(blank=True, max_length=31, null=True)),
                ("type", models.CharField(blank=True, max_length=31, null=True)),
                ("is_reviewed", models.BooleanField(default=False)),
                (
                    "marketplace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="marketplaces.marketplace",
                    ),
                ),
                (
                    "marketplace_edit_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crowdsourcing.marketplaceedit",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PhotoEdit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="crowdsourcing")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Descripción de la foto.",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("alt", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "marketplace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crowdsourcing.marketplaceedit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WebsiteEdit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("website", models.URLField(blank=True, max_length=127, null=True)),
                ("type", models.CharField(blank=True, max_length=31, null=True)),
                ("is_reviewed", models.BooleanField(default=False)),
                (
                    "marketplace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="marketplaces.marketplace",
                    ),
                ),
                (
                    "marketplace_edit_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crowdsourcing.marketplaceedit",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
