# Generated by Django 4.1.7 on 2023-04-22 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Committee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Marketplace",
            fields=[
                (
                    "marketplace_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=200)),
                ("name_alternate", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("opening_hours", models.CharField(max_length=1023)),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=16,
                        help_text="Latitud WGS 84 de la feria.",
                        max_digits=22,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=16,
                        help_text="Latitud WGS 84 de la feria.",
                        max_digits=22,
                    ),
                ),
                ("area", models.IntegerField(blank=True, null=True)),
                ("size", models.CharField(max_length=1)),
                (
                    "province",
                    models.IntegerField(
                        choices=[
                            (1, "San José"),
                            (2, "Alajuela"),
                            (3, "Cartago"),
                            (4, "Heredia"),
                            (5, "Guanacaste"),
                            (6, "Puntarenas"),
                            (7, "Limón"),
                        ]
                    ),
                ),
                (
                    "canton",
                    models.IntegerField(
                        help_text="Tres dígitos de código del cantón. Ver https://correos.go.cr/codigo-postal/."
                    ),
                ),
                (
                    "district",
                    models.IntegerField(
                        help_text="Cinco dígitos de código del distrito. Ver https://correos.go.cr/codigo-postal/."
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("phone", models.IntegerField(blank=True, null=True)),
                ("operator_center", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=63)),
                ("website", models.URLField(max_length=63)),
                ("opening_date", models.DateField()),
                ("fairground", models.BooleanField()),
                ("indoor", models.BooleanField()),
                ("toilets", models.BooleanField()),
                ("parking", models.BooleanField()),
                ("bicycle_parking", models.BooleanField()),
                ("drinking_water", models.BooleanField()),
                ("food", models.BooleanField()),
                ("drinks", models.BooleanField()),
                ("handicrafts", models.BooleanField()),
                ("flowers", models.BooleanField()),
                ("plants", models.BooleanField()),
                ("pet_food", models.BooleanField()),
                ("pet_friendly", models.BooleanField()),
                (
                    "operator_committee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="marketplaces.committee",
                    ),
                ),
                ("payment", models.ManyToManyField(to="marketplaces.payment")),
                ("products", models.ManyToManyField(to="products.product")),
            ],
        ),
    ]
