# Generated by Django 4.2.2 on 2023-07-10 20:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('marketplace_url', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=127)),
                ('name_alternate', models.CharField(blank=True, max_length=127, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('opening_hours', models.CharField(blank=True, max_length=1023, null=True)),
                ('opening_date', models.DateField(blank=True, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('area', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('province', models.CharField(max_length=31)),
                ('canton', models.CharField(max_length=31)),
                ('district', models.CharField(max_length=31)),
                ('postal_code', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('size', models.CharField(blank=True, choices=[('S', 'Pequeña'), ('M', 'Mediana'), ('L', 'Grande'), ('XL', 'Muy grande')], max_length=2, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=127, null=True)),
                ('website', models.URLField(blank=True, max_length=127, null=True)),
                ('operator', models.CharField(blank=True, max_length=255, null=True)),
                ('branch', models.CharField(blank=True, choices=[('Atlántico', 'Comité Regional Atlántico'), ('Brunca', 'Comité Regional Brunca'), ('Central Central', 'Comité Regional Central Central'), ('Central Occidental Este', 'Comité Regional Central Occidental Este'), ('Central Occidental Oeste', 'Comité Regional Central Occidental Oeste'), ('Central Oriental', 'Comité Regional Central Oriental'), ('Chorotega', 'Comité Regional Chorotega'), ('Huetar Norte', 'Comité Regional Huetar Norte'), ('Pacífico Central', 'Comité Regional Pacífico Central')], max_length=63, null=True)),
                ('parking', models.CharField(blank=True, choices=[('lane', 'en la calle'), ('street_side', 'al lado de la calle en espacio dedicado'), ('surface', 'un un espacio amplio de parqueo')], max_length=31, null=True)),
                ('bicycle_parking', models.BooleanField(blank=True, null=True)),
                ('fairground', models.BooleanField(blank=True, null=True)),
                ('indoor', models.BooleanField(blank=True, null=True)),
                ('toilets', models.BooleanField(blank=True, null=True)),
                ('handwashing', models.BooleanField(blank=True, null=True)),
                ('drinking_water', models.BooleanField(blank=True, null=True)),
                ('food', models.BooleanField(blank=True, null=True)),
                ('drinks', models.BooleanField(blank=True, null=True)),
                ('handicrafts', models.BooleanField(blank=True, null=True)),
                ('butcher', models.BooleanField(blank=True, null=True)),
                ('dairy', models.BooleanField(blank=True, null=True)),
                ('seafood', models.BooleanField(blank=True, null=True)),
                ('garden_centre', models.BooleanField(blank=True, null=True)),
                ('florist', models.BooleanField(blank=True, null=True)),
                ('other_services', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='marketplaces')),
                ('description', models.CharField(blank=True, help_text='Descripción de la foto (alt).', max_length=255, null=True)),
                ('profile', models.BooleanField(blank=True, default=False, null=True)),
                ('cover', models.BooleanField(blank=True, default=False, null=True)),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplaces.marketplace')),
            ],
        ),
        migrations.AddField(
            model_name='marketplace',
            name='payment',
            field=models.ManyToManyField(blank=True, to='marketplaces.payment'),
        ),
        migrations.AddField(
            model_name='marketplace',
            name='products',
            field=models.ManyToManyField(blank=True, to='products.product'),
        ),
    ]
