# Generated by Django 5.0.6 on 2024-10-10 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Allergy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allergy",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("gluten", "gluten"),
                            ("dairy", "lácteos"),
                            ("egg", "huevo"),
                            ("nuts", "nueces"),
                            ("soy", "soya"),
                            ("fish", "pescado"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=100, unique=True)),
                ("category_description", models.TextField(blank=True, null=True)),
                ("category_slug", models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_name", models.CharField(max_length=50, unique=True)),
                ("tag_slug", models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ingredient_name", models.CharField(max_length=100, unique=True)),
                ("ingredient_description", models.TextField(blank=True, null=True)),
                ("allergies", models.ManyToManyField(blank=True, to="recipes.allergy")),
                (
                    "ingredient_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.variety",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="recipes/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("cook_time", models.DurationField(blank=True, null=True)),
                ("prep_time", models.DurationField(blank=True, null=True)),
                ("total_time", models.DurationField(blank=True, null=True)),
                (
                    "recipe_yield",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "recipe_cuisine",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("storage", models.TextField(blank=True, null=True)),
                ("origin", models.TextField(blank=True, null=True)),
                ("references", models.TextField(blank=True, null=True)),
                ("nutritional_value", models.TextField(blank=True, null=True)),
                ("calories", models.CharField(blank=True, max_length=20, null=True)),
                ("fat_content", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "carbohydrate_content",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "protein_content",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="recipes.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecipeIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("g", "gramos"),
                            ("kg", "kilogramos"),
                            ("ml", "mililitros"),
                            ("l", "litros"),
                            ("tsp", "cucharadita"),
                            ("tbsp", "cucharada"),
                            ("cup", "taza"),
                            ("unit", "unidad"),
                            ("pinch", "pizca"),
                        ],
                        default="unit",
                        max_length=50,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=8)),
                (
                    "ingredient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="recipes.ingredient",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="recipes.recipe"
                    ),
                ),
            ],
            options={
                "unique_together": {("recipe", "ingredient")},
            },
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                through="recipes.RecipeIngredient", to="recipes.ingredient"
            ),
        ),
        migrations.CreateModel(
            name="Step",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_sequence", models.IntegerField()),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField()),
                ("photo", models.ImageField(blank=True, null=True, upload_to="steps/")),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="recipes.recipe"
                    ),
                ),
            ],
            options={
                "ordering": ["step_sequence"],
            },
        ),
        migrations.AddField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(blank=True, to="recipes.tag"),
        ),
    ]
