# Generated by Django 4.2.2 on 2023-07-10 20:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('code', models.CharField(help_text="Definición según 'From Vavilov to the Present: A Review' C. Earle Smith, Jr., Economic Botany, Vol. 23, No. 1 (Jan. - Mar., 1969), que va desde I hasta VIII.", max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=63)),
                ('description', models.TextField(blank=True, null=True)),
                ('region', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Preparation',
            fields=[
                ('preparation_url', models.CharField(max_length=31, primary_key=True, serialize=False)),
                ('method_name', models.CharField(max_length=63)),
                ('method_description', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_url', models.CharField(max_length=63, primary_key=True, serialize=False)),
                ('common_name', models.CharField(max_length=63)),
                ('common_name_alternate', models.CharField(blank=True, max_length=127, null=True)),
                ('category', models.CharField(choices=[('hortaliza', 'Hortaliza (verdura)'), ('fruta', 'Fruta'), ('cereal', 'Cereal (grano)'), ('legumbre', 'Legumbre (leguminosa)'), ('tubérculo', 'Tubérculo o raíz'), ('condimento', 'Condimento (especia)'), ('otro', 'Otra categoría')], max_length=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons')),
                ('food_basket', models.BooleanField(default=False)),
                ('nutrition_notes', models.TextField(blank=True, null=True)),
                ('preparation_notes', models.TextField(blank=True, null=True)),
                ('storage_notes', models.TextField(blank=True, null=True)),
                ('center_origin_notes', models.TextField(blank=True, null=True)),
                ('center_origin', models.ManyToManyField(blank=True, to='products.origin')),
                ('preparation', models.ManyToManyField(blank=True, to='products.preparation')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('storage_url', models.CharField(max_length=31, primary_key=True, serialize=False)),
                ('method_name', models.CharField(max_length=63)),
                ('method_description', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons')),
            ],
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('variety_id', models.AutoField(primary_key=True, serialize=False)),
                ('scientific_name', models.CharField(max_length=63)),
                ('scientific_name_variety', models.CharField(blank=True, max_length=63, null=True)),
                ('common_name_variety', models.CharField(blank=True, max_length=63, null=True)),
                ('common_name_variety_alternate', models.CharField(blank=True, max_length=127, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products')),
                ('jan', models.IntegerField(blank=True, choices=[(0, 'Sin disponibilidad'), (1, 'Poca disponibilidad'), (2, 'Buena disponibilidad'), (3, 'Temporada alta')], null=True)),
                ('feb', models.IntegerField(blank=True, choices=[(0, 'Sin disponibilidad'), (1, 'Poca disponibilidad'), (2, 'Buena disponibilidad'), (3, 'Temporada alta')], null=True)),
                ('mar', models.IntegerField(blank=True, choices=[(0, 'Sin disponibilidad'), (1, 'Poca disponibilidad'), (2, 'Buena disponibilidad'), (3, 'Temporada alta')], null=True)),
                ('apr', models.IntegerField(blank=True, choices=[(0, 'Sin disponibilidad'), (1, 'Poca disponibilidad'), (2, 'Buena disponibilidad'), (3, 'Temporada alta')], null=True)),
                ('may', models.IntegerField(blank=True, choices=[(0, 'Sin disponibilidad'), (1, 'Poca disponibilidad'), (2, 'Buena disponibilidad'), (3, 'Temporada alta')], null=True)),
                ('jun', models.IntegerField(blank=True, choices=[(0, 'Sin disponibilidad'), (1, 'Poca disponibilidad'), (2, 'Buena disponibilidad'), (3, 'Temporada alta')], null=True)),
                ('jul', models.IntegerField(blank=True, choices=[(0, 'Sin disponibilidad'), (1, 'Poca disponibilidad'), (2, 'Buena disponibilidad'), (3, 'Temporada alta')], null=True)),
                ('aug', models.IntegerField(blank=True, choices=[(0, 'Sin disponibilidad'), (1, 'Poca disponibilidad'), (2, 'Buena disponibilidad'), (3, 'Temporada alta')], null=True)),
                ('sep', models.IntegerField(blank=True, choices=[(0, 'Sin disponibilidad'), (1, 'Poca disponibilidad'), (2, 'Buena disponibilidad'), (3, 'Temporada alta')], null=True)),
                ('oct', models.IntegerField(blank=True, choices=[(0, 'Sin disponibilidad'), (1, 'Poca disponibilidad'), (2, 'Buena disponibilidad'), (3, 'Temporada alta')], null=True)),
                ('nov', models.IntegerField(blank=True, choices=[(0, 'Sin disponibilidad'), (1, 'Poca disponibilidad'), (2, 'Buena disponibilidad'), (3, 'Temporada alta')], null=True)),
                ('dec', models.IntegerField(blank=True, choices=[(0, 'Sin disponibilidad'), (1, 'Poca disponibilidad'), (2, 'Buena disponibilidad'), (3, 'Temporada alta')], null=True)),
                ('product_url', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='storage',
            field=models.ManyToManyField(blank=True, to='products.storage'),
        ),
    ]
